/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.wellington.apresentacao;

import br.edu.ifnmg.wellington.entidade.Usuario;
import br.edu.ifnmg.wellington.exception.CampoObrigatorioException;
import br.edu.ifnmg.wellington.exception.VerificarUsuarioDuplicado;
import br.edu.ifnmg.wellington.negocio.UsuarioBO;
import java.io.UnsupportedEncodingException;
import java.security.NoSuchAlgorithmException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Were
 */
public class FormAddUsuario extends javax.swing.JFrame {

    private Usuario usuarioEmEdicao;
    private UsuarioBO usuarioBO;
    private Home home;
    int flagEditarUsuario = 0;

    public FormAddUsuario(Home telaHome) {
        this.home = telaHome;
        initComponents();
    }

    public FormAddUsuario(Usuario u, Home telaHome, int flag) {
        this.home = telaHome;
        this.usuarioEmEdicao = u;
        this.flagEditarUsuario = flag;
        initComponents();
        this.preencherCamposTela(usuarioEmEdicao);
    }

    public FormAddUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtAddLogin = new javax.swing.JTextField();
        lblAddLogin = new javax.swing.JLabel();
        lblAddSenha = new javax.swing.JLabel();
        txtAddSenhaUsuario = new javax.swing.JPasswordField();
        cbxTipoUser = new javax.swing.JComboBox<>();
        lblAddTipoUsuario = new javax.swing.JLabel();
        btnSalvarUsuario = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        lblDica = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Usuário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        lblAddLogin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAddLogin.setText("Login:");

        lblAddSenha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAddSenha.setText("Senha:");

        cbxTipoUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "Administrador", "Atendente" }));

        lblAddTipoUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAddTipoUsuario.setText("Tipo");

        btnSalvarUsuario.setText("Salvar");
        btnSalvarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarUsuarioActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnVoltar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnSalvarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblAddLogin)
                                .addComponent(lblAddSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtAddSenhaUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                                .addComponent(txtAddLogin)
                                .addComponent(lblDica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblAddTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxTipoUser, 0, 228, Short.MAX_VALUE)))
                .addContainerGap(161, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblAddLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAddLogin))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblAddSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAddSenhaUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDica, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxTipoUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddTipoUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSalvarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(126, 126, 126))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarUsuarioActionPerformed
        if (flagEditarUsuario != 1) {
            try {
                this.incluirUsuario();
                this.home.carregarTabelaDeUsuarios();
            } catch (NoSuchAlgorithmException ex) {
                Logger.getLogger(FormAddVeiculo.class.getName()).log(Level.SEVERE, null, ex);
            } catch (UnsupportedEncodingException ex) {
                Logger.getLogger(FormAddVeiculo.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(FormAddVeiculo.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            try {
                this.editarUsuario();
            } catch (SQLException ex) {
                Logger.getLogger(FormAddUsuario.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NoSuchAlgorithmException ex) {
                Logger.getLogger(FormAddUsuario.class.getName()).log(Level.SEVERE, null, ex);
            } catch (UnsupportedEncodingException ex) {
                Logger.getLogger(FormAddUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.flagEditarUsuario = 0;
        }
    }//GEN-LAST:event_btnSalvarUsuarioActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.limparCamposTelaNovoUsuario();
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvarUsuario;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> cbxTipoUser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAddLogin;
    private javax.swing.JLabel lblAddSenha;
    private javax.swing.JLabel lblAddTipoUsuario;
    private javax.swing.JLabel lblDica;
    private javax.swing.JTextField txtAddLogin;
    private javax.swing.JPasswordField txtAddSenhaUsuario;
    // End of variables declaration//GEN-END:variables

    private void incluirUsuario() throws NoSuchAlgorithmException, UnsupportedEncodingException, SQLException {
        try {
            this.usuarioBO = new UsuarioBO();
            this.recuperarCamposFormNovoUsuario();
            this.usuarioBO.verificauUsuarioDuplicado(this.usuarioEmEdicao);
            this.usuarioBO.incluirUsuario(this.usuarioEmEdicao);
            JOptionPane.showMessageDialog(this, "Cadastrado com sucesso!", "Novo usuário", JOptionPane.INFORMATION_MESSAGE);
            this.limparCamposFormNovoUsuario();
        } catch (CampoObrigatorioException c) {
            String mensagen = "Por favor, Preencha todos os campos!\n" + c.getMessage();
            JOptionPane.showMessageDialog(this, mensagen, "Novo usuario", JOptionPane.ERROR_MESSAGE);
        } catch (VerificarUsuarioDuplicado v) {
            JOptionPane.showMessageDialog(this, v.getMessage(), "Novo usuário", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void editarUsuario() throws SQLException, NoSuchAlgorithmException, UnsupportedEncodingException {
        //    try {
        this.usuarioBO = new UsuarioBO();
        int i = JOptionPane.showConfirmDialog(this, "Tem Certeza?", "Edição de usuário", JOptionPane.YES_NO_OPTION);
        if (i == JOptionPane.NO_OPTION) {
            this.dispose();
        } else {
            this.recuperarCamposFormNovoUsuario();
            this.usuarioBO.atualizarUsuario(this.usuarioEmEdicao);
            JOptionPane.showMessageDialog(this, "Alterado com sucesso!", "Edição de veículo", JOptionPane.INFORMATION_MESSAGE);
            this.limparCamposFormNovoUsuario();
            this.home.carregarTabelaDeUsuarios();
            this.dispose();
        }
//        } catch (RuntimeException r) {
//            JOptionPane.showMessageDialog(this, "algum campo está vazio", "Edição de veículo", JOptionPane.INFORMATION_MESSAGE);
//        }
    }

    private void limparCamposFormNovoUsuario() {
        this.txtAddLogin.setText("");
        this.txtAddSenhaUsuario.setText("");
        this.cbxTipoUser.setSelectedIndex(0);
    }

    private void recuperarCamposFormNovoUsuario() {
        if (this.usuarioEmEdicao == null) {
            this.usuarioEmEdicao = new Usuario();
        }

        if (txtAddLogin.getText().equals("")) {
            throw new CampoObrigatorioException("Campo LOGIN vazio!");
        } else {
            this.usuarioEmEdicao.setLogin(txtAddLogin.getText());
        }

        if (txtAddSenhaUsuario.getText().equals("")) {
            throw new CampoObrigatorioException("Campo SENHA vazio!");
        } else {
            this.usuarioEmEdicao.setSenha(txtAddSenhaUsuario.getText());
        }

        if (cbxTipoUser.getSelectedItem().equals("--")) {
            throw new CampoObrigatorioException("Selecione o tipo de usuário");
        } else if (cbxTipoUser.getSelectedItem().equals("Administrador")) {
            this.usuarioEmEdicao.setTipo(1);
        } else {
            this.usuarioEmEdicao.setTipo(0);
        }

    }

    private void preencherCamposTela(Usuario usuarioEmEdicao) {
        this.txtAddLogin.setText(usuarioEmEdicao.getLogin());
        this.txtAddSenhaUsuario.setText("");
        this.lblDica.setText("se não for alterar não preencha este campo!");
        this.cbxTipoUser.setSelectedItem(usuarioEmEdicao.getTipo());
    }

    private void limparCamposTelaNovoUsuario() {
        this.txtAddLogin.setText("");
        this.txtAddSenhaUsuario.setText("");
        this.lblDica.setText("");
        this.cbxTipoUser.setSelectedItem(0);
    }

}
